# Settings to access CROC Cloud using public API
export C2_PROJECT="xxx"
export S3_URL="xxx"
export EC2_URL="xxx"
export EKS_URL="xxx"
export AWS_CLOUDWATCH_URL="xxx"
export AWS_CLOUDTRAIL_URL="xxx"
export EC2_ACCESS_KEY="xxx"
export EC2_SECRET_KEY="xxx"
export AWS_ACCESS_KEY_ID="xxx"
export AWS_SECRET_ACCESS_KEY="xxx"
